version: '4.17'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports: 
      - "4004:389"
      - "4005:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment: 
      - LDAP_ORGANISATION=pawsomenetwork
      - LDAP_DOMAIN=pawsomenetwork.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - LDAP_BASE_DN=dc=pawsomenetwork,dc=com
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=pawsomenetwork.com.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro_pass
    networks:
      - psn_network
  
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports: 
      - "4003:80"
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - psn_network

  psn-authentication-db:
    build: ./psn_authentication/psn_authentication_db
    container_name: psn-authentication-db
    hostname: psn-authentication-db
    ports:
      - "4001:3306"
    networks:
      - psn_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "4002:80"
    environment:
      PMA_HOST: psn-authentication-db
    depends_on:
      - psn-authentication-db
    networks:
      - psn_network

  psn-authentication-ms:
    build: ./psn_authentication/psn_authentication_ms
    container_name: psn-authentication-ms
    hostname: psn-authentication-ms
    ports:
      - "4000:4000"
    depends_on:
      - psn-authentication-db
      - openldap
    networks:
      - psn_network

  psn-ur-db:
    image: neo4j
    container_name: psn-ur-db
    ports:
      - 4201:7474
      - 4202:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/psn12345
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
    networks:
      - psn_network

  psn-ur-ms:
    image: psn-ur-ms
    build: ./psn_user_relationships_ms
    container_name: psn-ur-ms
    ports:
      - "4200:4200"
    volumes:
      - "./psn_user_relationships_ms:/psn-ur-ms"
    networks:
      - psn_network

  psn-posts-ms:
    build: ./psn_post_ms
    container_name: psn-posts-ms
    ports:
      - "4100:4100"
    networks:
      - psn_network

  psn-chat-ms:
    image: psn-chat-ms
    build: ./psn-chat-ms
    container_name: psn-chat-ms
    env_file:
      - ./psn-chat-ms/.env
    ports:
      - "4300:4300"
    networks:
      - psn_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "4402:5672"
      - "4403:15672"
    env_file:
      - ./psn-notification-ms/.env
    networks:
      - psn_network

  psn-notification-ms:
    image: psn-notification-ms
    build: ./psn-notification-ms
    container_name: psn-notification-ms
    env_file:
      - ./psn-notification-ms/.env
    ports:
      - "4400:4400"
    depends_on: 
      - rabbitmq
    networks:
      - psn_network
    
  psn-notification-ws-ms:
    image: psn-notification-ws-ms
    build: ./psn-notification-ws-ms
    container_name: psn-notification-ws-ms
    env_file:
      - ./psn-notification-ws-ms/.env
    ports:
      - "4401:4401"
    depends_on: 
      - rabbitmq
    networks:
      - psn_network

  psn-ag:
    image: psn-ag
    build: ./psn_ag
    container_name: psn-ag
    expose:
      - "4500"
    ports:
      - "4500:4500"
    networks:
      - psn_network

networks:
  psn_network:
    driver: bridge