apiVersion: apps/v1
kind: Deployment
metadata:
  name: psn-authentication-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psn-authentication-ms
  template:
    metadata:
      labels:
        app: psn-authentication-ms
    spec:
      containers:
      - name: psn-authentication-ms
        image: julian9999/psn-authentication-ms:v1.0
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: psn-authentication-db-service
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: psn_admin
        - name: DB_PASSWORD
          value: "123"
        - name: DB_NAME
          value: psn-authentication-db
        - name: PSN_WA
          value: https://34.73.14.6

        - name: LDAP_HOST
          value: psn-openldap-service
        - name: LDAP_PORT
          value: "389"
        - name: LDAP_BASE
          value: dc=pawsomenetwork,dc=com
        - name: LDAP_USER
          value: cn=admin,dc=pawsomenetwork,dc=com
        - name: LDAP_PASSWORD
          value: admin_pass

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: psn-interface-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psn-interface
  template:
    metadata:
      labels:
        app: psn-interface
    spec:
      containers:
        - name: psn-interface
          image: julian9999/psn-interface:v1.0
          ports:
            - containerPort: 4700

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: psn-interface-rp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psn-interface-rp
  template:
    metadata:
      labels:
        app: psn-interface-rp
    spec:
      containers:
        - name: psn-interface-rp
          image: julian9999/psn-interface-rp:v1.0
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: psn-authentication-ms-service
spec:
  selector:
    app: psn-authentication-ms
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: psn-interface-service
spec:
  selector:
    app: psn-interface
  ports:
  - name: http
    protocol: TCP
    port: 4700
    targetPort: 4700
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: psn-interface-rp-service
spec:
  selector:
    app: psn-interface-rp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer