apiVersion: apps/v1
kind: Deployment
metadata:
  name: psn-ag-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psn-ag
  template:
    metadata:
      labels:
        app: psn-ag
    spec:
      containers:
      - name: psn-ag
        image: julian9999/psn-ag:v1.0
        ports:
        - containerPort: 4500
        env:
        - name: SERVICE_ACCOUNT_FILE
          value: /psn_ag/psn.json
        - name: BUCKET_NAME
          value: psn_bucket1
      imagePullSecrets:
        - name: psn-ag-secret

---

apiVersion: v1
kind: Service
metadata:
  name: psn-ag-service
spec:
  selector:
    app: psn-ag
  ports:
  - name: http
    protocol: TCP
    port: 4500
    targetPort: 4500
  type: LoadBalancer

---