apiVersion: apps/v1
kind: Deployment
metadata:
  name: psn-interface-rp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psn-interface-rp
  template:
    metadata:
      labels:
        app: psn-interface-rp
    spec:
      containers:
        - name: psn-interface-rp
          image: julian9999/psn-interface-rp:v1.0
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: psn-interface-rp-service
spec:
  selector:
    app: psn-interface-rp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---