apiVersion: apps/v1
kind: Deployment
metadata:
  name: psn-phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psn-phpmyadmin
  template:
    metadata:
      labels:
        app: psn-phpmyadmin
    spec:
      containers:
      - name: psn-phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: "10.0.2.3"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 60

---

apiVersion: v1
kind: Service
metadata:
  name: psn-phpmyadmin-service
spec:
  selector:
    app: psn-phpmyadmin
  ports:
  - name: http
    port: 4002
    targetPort: 80
  type: LoadBalancer

---