apiVersion: v1
kind: Service
metadata:
  name: psn-interface-service
spec:
  selector:
    app: psn-interface
  ports:
  - name: http
    protocol: TCP
    port: 4700
    targetPort: 4700
  type: LoadBalancer